// ============================================
// NMTI 4-axis data model
// ============================================

const AXES = {
  drive: {
    name: '投入轴',
    icon: '🔥',
    negative: { code: 'J', label: '卷型', short: '卷', desc: '主动推进、愿意多扛一点，把结果放在舒服前面。' },
    positive: { code: 'T', label: '躺型', short: '躺', desc: '重视边界和可持续，不轻易把生活交给工作。' },
  },
  survival: {
    name: '生存轴',
    icon: '🧰',
    negative: { code: 'G', label: '工型', short: '工', desc: '解决问题优先，倾向硬扛、补位、把事情落地。' },
    positive: { code: 'Y', label: '鱼型', short: '鱼', desc: '保存能量优先，擅长观察节奏、避开无效消耗。' },
  },
  belief: {
    name: '信念轴',
    icon: '🥞',
    negative: { code: 'B', label: '饼型', short: '饼', desc: '更愿意相信未来、机会和组织承诺。' },
    positive: { code: 'X', label: '醒型', short: '醒', desc: '更看重现实回报、边界和可验证的条件。' },
  },
  expression: {
    name: '表达轴',
    icon: '🗣️',
    negative: { code: 'K', label: '锅型', short: '锅', desc: '习惯先接住局面，少说多扛，冲突能避则避。' },
    positive: { code: 'Z', label: '嘴型', short: '嘴', desc: '习惯把话说清楚，敢吐槽、敢谈边界。' },
  },
};

const AXIS_ORDER = ['drive', 'survival', 'belief', 'expression'];

const QUESTIONS = [
  { id: 1, axis: 'drive', text: '下班前突然多了一个“明早要”的任务，你更接近？',
    options: [
      { text: '直接开干，今晚先把结果顶出来', score: -2 },
      { text: '先做关键部分，能推进多少是多少', score: -1 },
      { text: '确认优先级，能明天做就不今晚硬扛', score: 1 },
      { text: '明确边界：临时需求不默认占用下班时间', score: 2 },
    ]},
  { id: 2, axis: 'drive', text: '团队里没人主动接一个麻烦活时，你通常会？',
    options: [
      { text: '我来吧，别拖着影响整体进度', score: -2 },
      { text: '如果确实没人接，我会补位', score: -1 },
      { text: '先看是不是我的职责范围', score: 1 },
      { text: '不主动接，避免变成长期默认负责人', score: 2 },
    ]},
  { id: 3, axis: 'drive', text: '你对“成长型挑战”的真实反应是？',
    options: [
      { text: '越难越想试，最好能证明自己', score: -2 },
      { text: '有挑战可以，但要看投入产出', score: -1 },
      { text: '能稳定做好本职就不错', score: 1 },
      { text: '听到挑战就想先看看是不是画饼', score: 2 },
    ]},
  { id: 4, axis: 'drive', text: '周末收到工作消息，你会？',
    options: [
      { text: '马上处理，不想让事情悬着', score: -2 },
      { text: '先看紧急程度，重要就回', score: -1 },
      { text: '看到但不急，工作日再处理', score: 1 },
      { text: '除非真出事故，否则不回', score: 2 },
    ]},
  { id: 5, axis: 'drive', text: '如果一个项目能让你露脸，但会明显更累，你会？',
    options: [
      { text: '接，机会来了就要抓住', score: -2 },
      { text: '接，但会提前谈资源和排期', score: -1 },
      { text: '犹豫，露脸不一定抵得上消耗', score: 1 },
      { text: '不接，稳定生活更重要', score: 2 },
    ]},
  { id: 6, axis: 'drive', text: '你更像哪种工作节奏？',
    options: [
      { text: '主动拉满，把事情往前推', score: -2 },
      { text: '有目标时会明显加速', score: -1 },
      { text: '按节奏完成，不额外加戏', score: 1 },
      { text: '能低耗完成就绝不高耗', score: 2 },
    ]},
  { id: 7, axis: 'drive', text: '同事都在卷一个新机会时，你会？',
    options: [
      { text: '跟上，不能输在起跑线', score: -2 },
      { text: '挑有价值的部分参与', score: -1 },
      { text: '观察一下，不急着冲', score: 1 },
      { text: '不卷，别人的节奏别带走我', score: 2 },
    ]},
  { id: 8, axis: 'drive', text: '你最不能接受的工作状态是？',
    options: [
      { text: '没目标、没产出、像在空转', score: -2 },
      { text: '做了很多但没人看见', score: -1 },
      { text: '每天都被催着往前冲', score: 1 },
      { text: '工作持续侵占生活', score: 2 },
    ]},

  { id: 9, axis: 'survival', text: '遇到一个没人会处理的问题，你会？',
    options: [
      { text: '先拆解，试到能跑为止', score: -2 },
      { text: '查资料、问人、先推进起来', score: -1 },
      { text: '先判断这是不是我该解决的', score: 1 },
      { text: '尽量别把问题揽到自己身上', score: 2 },
    ]},
  { id: 10, axis: 'survival', text: '工作空档期，你通常会？',
    options: [
      { text: '补文档、清任务、顺手优化', score: -2 },
      { text: '整理一下，保持随时能接活', score: -1 },
      { text: '放松一下，别让自己一直在线', score: 1 },
      { text: '正式进入低功耗模式', score: 2 },
    ]},
  { id: 11, axis: 'survival', text: '老板突然问你“这个能不能搞一下”，你会？',
    options: [
      { text: '能，我先接住再说', score: -2 },
      { text: '我先评估，能做就给方案', score: -1 },
      { text: '要看优先级和现有排期', score: 1 },
      { text: '先别急着答应，避免变成默认工具人', score: 2 },
    ]},
  { id: 12, axis: 'survival', text: '你摸鱼时最在意什么？',
    options: [
      { text: '不太摸，手里总得有点事', score: -2 },
      { text: '别影响正事，其他都好说', score: -1 },
      { text: '要能随时切回工作状态', score: 1 },
      { text: '要安静、完整、没人打扰', score: 2 },
    ]},
  { id: 13, axis: 'survival', text: '别人评价你“很好用”，你会？',
    options: [
      { text: '说明我靠谱，挺好', score: -2 },
      { text: '认可，但希望别滥用', score: -1 },
      { text: '有点警惕，别什么都找我', score: 1 },
      { text: '不想当好用的人，只想当难被消耗的人', score: 2 },
    ]},
  { id: 14, axis: 'survival', text: '一个会开很久但和你关系不大的会议，你会？',
    options: [
      { text: '认真听，也许能补到信息', score: -2 },
      { text: '听关键部分，顺手处理点小事', score: -1 },
      { text: '保持在线，但尽量低消耗', score: 1 },
      { text: '能不去就不去，去了也开静音', score: 2 },
    ]},
  { id: 15, axis: 'survival', text: '任务堆起来时，你优先做什么？',
    options: [
      { text: '按影响面排序，一个个清掉', score: -2 },
      { text: '先处理最急最卡人的', score: -1 },
      { text: '先保住自己负责的范围', score: 1 },
      { text: '先找能少做一点的办法', score: 2 },
    ]},
  { id: 16, axis: 'survival', text: '你对“能者多劳”的态度是？',
    options: [
      { text: '能做就做，事情不能没人管', score: -2 },
      { text: '可以多做，但要被看见', score: -1 },
      { text: '多劳可以，多得也要跟上', score: 1 },
      { text: '这句话通常是压榨的开场白', score: 2 },
    ]},

  { id: 17, axis: 'belief', text: '领导说“明年一定给你更大空间”，你会？',
    options: [
      { text: '愿意相信，先把眼前做好', score: -2 },
      { text: '会期待，但也会留个心眼', score: -1 },
      { text: '先问清楚标准和兑现方式', score: 1 },
      { text: '没有合同和资源，就先当故事听', score: 2 },
    ]},
  { id: 18, axis: 'belief', text: '你怎么看“公司好了，大家都会好”？',
    options: [
      { text: '大方向是对的，值得一起努力', score: -2 },
      { text: '有道理，但要看分配是否公平', score: -1 },
      { text: '不一定，公司好不等于我好', score: 1 },
      { text: '典型大饼话术，先看工资条', score: 2 },
    ]},
  { id: 19, axis: 'belief', text: '面对一个听起来很美的新项目，你会？',
    options: [
      { text: '先被点燃，想参与进去', score: -2 },
      { text: '有兴趣，边做边看', score: -1 },
      { text: '先看资源、排期和负责人', score: 1 },
      { text: '先找风险点，别被愿景带跑', score: 2 },
    ]},
  { id: 20, axis: 'belief', text: '你对“努力就会有回报”的感觉是？',
    options: [
      { text: '我还是愿意相信这句话', score: -2 },
      { text: '多数时候有用，至少能增加机会', score: -1 },
      { text: '努力只是条件之一', score: 1 },
      { text: '回报要靠规则，不靠感动', score: 2 },
    ]},
  { id: 21, axis: 'belief', text: '当团队士气低落时，你更可能？',
    options: [
      { text: '帮大家打气，先把气氛撑起来', score: -2 },
      { text: '说点积极的，但不夸大', score: -1 },
      { text: '少讲口号，多说具体问题', score: 1 },
      { text: '直接指出真实困境，别互相催眠', score: 2 },
    ]},
  { id: 22, axis: 'belief', text: '你收到一段老板激情演讲后的反应是？',
    options: [
      { text: '有被鼓舞到，想再冲一冲', score: -2 },
      { text: '有些部分能听进去', score: -1 },
      { text: '听完会自动提取可执行信息', score: 1 },
      { text: '先判断哪些是话术、哪些是承诺', score: 2 },
    ]},
  { id: 23, axis: 'belief', text: '你更希望工作给你什么？',
    options: [
      { text: '成长、机会和更好的未来', score: -2 },
      { text: '稳定成长和适度认可', score: -1 },
      { text: '清晰回报和明确边界', score: 1 },
      { text: '少讲愿景，多给确定性', score: 2 },
    ]},

  { id: 24, axis: 'expression', text: '项目出问题时，别人先来找你，你会？',
    options: [
      { text: '先接住，别让事情继续炸', score: -2 },
      { text: '先处理问题，责任之后再说', score: -1 },
      { text: '同步事实，别默认我背锅', score: 1 },
      { text: '当场讲清边界和责任归属', score: 2 },
    ]},
  { id: 25, axis: 'expression', text: '会议里出现明显不合理安排，你会？',
    options: [
      { text: '先记下来，会后自己消化', score: -2 },
      { text: '委婉提醒一下风险', score: -1 },
      { text: '直接提出疑问和替代方案', score: 1 },
      { text: '当场说清楚为什么不合理', score: 2 },
    ]},
  { id: 26, axis: 'expression', text: '被临时甩锅时，你的第一反应是？',
    options: [
      { text: '先别吵，赶紧把局面稳住', score: -2 },
      { text: '先处理，再找机会解释', score: -1 },
      { text: '马上补充上下文，防止误会扩大', score: 1 },
      { text: '直接说明这不是我的责任', score: 2 },
    ]},
  { id: 27, axis: 'expression', text: '你在工作群里的发言风格更像？',
    options: [
      { text: '必要才说，尽量别引发冲突', score: -2 },
      { text: '客观同步，少表达情绪', score: -1 },
      { text: '该提醒就提醒，该吐槽也会吐槽', score: 1 },
      { text: '不合理就说，沉默只会让问题变大', score: 2 },
    ]},
  { id: 28, axis: 'expression', text: '同事让你帮一个明显越界的忙，你会？',
    options: [
      { text: '先帮一次，别把关系弄僵', score: -2 },
      { text: '能帮一点是一点，但不说太重', score: -1 },
      { text: '说明我能帮到哪里、不能帮哪里', score: 1 },
      { text: '直接拒绝，边界要从第一次开始', score: 2 },
    ]},
  { id: 29, axis: 'expression', text: '你对“忍一忍就过去了”的态度是？',
    options: [
      { text: '很多事确实忍过去就好了', score: -2 },
      { text: '小事可以忍，大事再说', score: -1 },
      { text: '忍之前先判断代价', score: 1 },
      { text: '很多问题就是被忍出来的', score: 2 },
    ]},
  { id: 30, axis: 'expression', text: '当你觉得自己被低估时，你会？',
    options: [
      { text: '继续做，总有人会看见', score: -2 },
      { text: '找机会证明，但不主动争', score: -1 },
      { text: '主动沟通贡献和期待', score: 1 },
      { text: '直接谈评价、待遇和资源', score: 2 },
    ]},
];

const RESULT_TYPES = {
  JGBK: {
    key: 'JGBK', name: '燃尽合伙人', emoji: '🔥', color: '#ef4444',
    slogan: '公司没我得散，但我快散了。',
    summary: '高投入、强落地、愿意相信，也习惯先扛住。',
    desc: '你像一个没有股份的合伙人，既相信未来，也愿意把最麻烦的活接住。你不是不知道累，只是事情摆在面前时，很难真的放着不管。',
    profile: '适合复杂项目和关键节点，但要警惕长期被默认成救火位。',
    advice: '给热情配上边界，别让责任感替别人买单。',
    traits: ['高投入', '强补位', '愿景驱动', '隐忍背锅'],
  },
  JGBZ: {
    key: 'JGBZ', name: '画饼冲锋官', emoji: '🥞', color: '#f97316',
    slogan: '饼可以吃，但我要边冲边说。',
    summary: '高投入、强执行、愿景感强，同时表达欲在线。',
    desc: '你容易被目标点燃，也愿意冲在前面。不同的是你不会只默默干活，哪里不合理、哪里需要资源，你会直接讲出来。',
    profile: '适合开荒、推动和对外沟通，但容易在热血和吐槽之间来回横跳。',
    advice: '把表达变成谈条件，不只是情绪输出。',
    traits: ['冲锋', '乐观', '敢说', '推动型'],
  },
  JGXK: {
    key: 'JGXK', name: '清醒救火队长', emoji: '🧯', color: '#dc2626',
    slogan: '我知道这是坑，但火总得有人灭。',
    summary: '高投入、强落地、现实清醒，且常常先接住局面。',
    desc: '你看得懂规则和风险，却依然会在关键时刻站出来。你不是被饼骗住，而是对事情本身有责任感。',
    profile: '适合危机处理和复杂协调，但容易把清醒活成疲惫。',
    advice: '救火前先确认谁负责添柴。',
    traits: ['救火', '清醒', '抗压', '责任感'],
  },
  JGXZ: {
    key: 'JGXZ', name: '边界推进官', emoji: '📌', color: '#8b5cf6',
    slogan: '事情要做，边界也要谈。',
    summary: '高投入、强落地、现实判断强，且表达边界清楚。',
    desc: '你既能推进结果，也不会轻易接受模糊责任。你相信专业推动，而不是靠感动加班。',
    profile: '适合做项目负责人、流程 owner 和关键接口人。',
    advice: '继续把问题讲清楚，你的锋利是效率的一部分。',
    traits: ['推进', '谈判', '边界', '结果导向'],
  },
  JYBK: {
    key: 'JYBK', name: '暗线苦劳人', emoji: '🕯️', color: '#f59e0b',
    slogan: '表面低调，背后全是我在补。',
    summary: '高投入、低耗生存、愿意相信，且倾向默默扛事。',
    desc: '你不是不会摸鱼，只是关键时刻还是会把事情补上。你会给组织和同事留余地，也常常把委屈留给自己。',
    profile: '适合稳定团队基本盘，但容易功劳隐身、压力内化。',
    advice: '别只做暗线，关键贡献要留痕。',
    traits: ['低调', '苦劳', '补位', '愿景感'],
  },
  JYBZ: {
    key: 'JYBZ', name: '气氛冲锋鱼', emoji: '🐟', color: '#06b6d4',
    slogan: '能摸也能冲，主要看值不值得。',
    summary: '高投入、会保存能量、愿意相信，同时表达活跃。',
    desc: '你有冲劲，也懂节奏。你会被好故事调动，但不会完全失去自我保护；你能带气氛，也能把不满说出来。',
    profile: '适合创意协作、团队破冰和轻量推进。',
    advice: '别让气氛感代替真正的资源和承诺。',
    traits: ['灵活', '气氛组', '会冲', '会说'],
  },
  JYXK: {
    key: 'JYXK', name: '隐忍拆弹师', emoji: '🧩', color: '#64748b',
    slogan: '我都看懂了，但先把雷拆掉。',
    summary: '高投入、低耗生存、现实清醒，且常先忍住。',
    desc: '你擅长在混乱里找出真正的问题，低调处理风险。你不太相信空话，但会为了结果暂时忍下很多东西。',
    profile: '适合风险识别、收尾和复杂问题拆解。',
    advice: '别总把拆弹变成无声奉献。',
    traits: ['清醒', '低调', '拆雷', '耐受'],
  },
  JYXZ: {
    key: 'JYXZ', name: '反卷策略家', emoji: '♟️', color: '#0ea5e9',
    slogan: '我不是不努力，我是拒绝无效燃烧。',
    summary: '高投入、懂低耗、现实清醒，且表达边界明确。',
    desc: '你会投入值得做的事，也会拒绝没有意义的消耗。你不是摆烂，而是在用策略对抗无效内卷。',
    profile: '适合策略规划、资源协调和流程优化。',
    advice: '把你的判断沉淀成方法，而不是只留在吐槽里。',
    traits: ['策略', '反卷', '边界', '效率'],
  },
  TGBK: {
    key: 'TGBK', name: '温吞工具人', emoji: '🧰', color: '#a16207',
    slogan: '我不想卷，但活还是会做完。',
    summary: '重边界、强落地、愿意相信，且倾向接住局面。',
    desc: '你不追求高光，但很可靠。别人可能觉得你温和好说话，于是把不少琐碎和补位工作放到你这里。',
    profile: '适合稳定执行和支持型岗位，但容易被低估。',
    advice: '温和不等于无限可用。',
    traits: ['稳定', '工具人', '温和', '能扛'],
  },
  TGBZ: {
    key: 'TGBZ', name: '佛系协调员', emoji: '🤝', color: '#22c55e',
    slogan: '能做好，也能好好说。',
    summary: '重边界、强落地、愿意相信，同时表达较开放。',
    desc: '你不爱卷，但愿意把事情协调顺。你对未来保留善意，也能用比较舒服的方式把问题说出来。',
    profile: '适合跨团队协作、支持协调和稳定交付。',
    advice: '保持松弛，但别把所有关系都靠你来圆。',
    traits: ['协调', '佛系', '稳定', '表达'],
  },
  TGXK: {
    key: 'TGXK', name: '静默补位者', emoji: '🪨', color: '#475569',
    slogan: '不争不抢，但该补的我会补。',
    summary: '重边界、强落地、现实清醒，且多半安静承受。',
    desc: '你不太相信大饼，也不想成为焦点，但事情真没人做时，你还是会安静补上。你的存在感不高，可靠度很高。',
    profile: '适合维护系统稳定，但要避免长期隐形劳动。',
    advice: '把补位说出来，不然别人会以为它自动发生。',
    traits: ['静默', '补位', '清醒', '可靠'],
  },
  TGXZ: {
    key: 'TGXZ', name: '边界维护员', emoji: '🛡️', color: '#2563eb',
    slogan: '做好我的事，也守住我的线。',
    summary: '重边界、强落地、现实清醒，且会表达边界。',
    desc: '你是成熟的职场稳定器：该做的做清楚，不该背的也会讲清楚。你不靠热血工作，靠规则和质量工作。',
    profile: '适合标准化流程、质量把关和长期协作。',
    advice: '继续守线，你的清晰能保护自己也保护项目。',
    traits: ['边界', '稳定', '规则', '质量'],
  },
  TYBK: {
    key: 'TYBK', name: '低耗许愿家', emoji: '🌙', color: '#14b8a6',
    slogan: '希望会好，但我先省点电。',
    summary: '重边界、低耗生存、愿意相信，且习惯先忍让。',
    desc: '你对未来还有期待，但不会为了期待无限燃烧。你更喜欢低消耗地待在系统里，能过就过，能少冲就少冲。',
    profile: '适合节奏稳定的环境，但容易在等待中错过主动改变。',
    advice: '愿望要配行动，不然只会变成草稿箱。',
    traits: ['低耗', '许愿', '温和', '忍让'],
  },
  TYBZ: {
    key: 'TYBZ', name: '快乐画饼鱼', emoji: '🎈', color: '#ec4899',
    slogan: '先快乐一点，明天也许会好。',
    summary: '重边界、低耗生存、愿意相信，且表达轻快。',
    desc: '你擅长用轻松感对抗职场压力。你相信事情可能变好，但不会把自己全部押上；吐槽和玩笑是你的自救方式。',
    profile: '适合轻松协作和创意氛围，但要警惕逃避关键问题。',
    advice: '快乐很好，关键选择也要认真做。',
    traits: ['快乐', '低耗', '乐观', '会吐槽'],
  },
  TYXK: {
    key: 'TYXK', name: '人间清醒韭', emoji: '🌱', color: '#10b981',
    slogan: '看透了，先活着。',
    summary: '重边界、低耗生存、现实清醒，且偏向隐忍。',
    desc: '你很清楚职场规则，也知道自己不该被过度消耗。只是很多时候你选择先保全自己，低调穿过周期。',
    profile: '适合低波动环境，但可能压抑真实诉求。',
    advice: '清醒之外，也要给自己留一点行动空间。',
    traits: ['清醒', '低耗', '隐忍', '自保'],
  },
  TYXZ: {
    key: 'TYXZ', name: '终极躺平嘴替', emoji: '🛋️', color: '#7c3aed',
    slogan: '我不卷，也不装没看见。',
    summary: '重边界、低耗生存、现实清醒，且敢于表达。',
    desc: '你已经把职场看得很透：不无效燃烧，不替话术买单，也不轻易沉默。你的躺平不是放弃，而是把主动权拿回自己手里。',
    profile: '适合边界清晰、尊重自主的环境。',
    advice: '锋利很好，也记得保留建设性的出口。',
    traits: ['躺平', '清醒', '嘴替', '边界'],
  },
  default: {
    key: 'default', name: '混合型牛马', emoji: '🐴', color: '#f59e0b',
    slogan: '今天的我，也很复杂。',
    summary: '四轴结果接近中间值。',
    desc: '你的答案呈现出较强的混合特征，不太能被单一路径概括。',
    profile: '适合根据环境灵活调整，但需要确认自己真正想要什么。',
    advice: '先分清哪些是策略，哪些是委屈。',
    traits: ['混合', '灵活', '复杂'],
  },
};

const RESULT_IMAGE_BASE = 'img/generated/roles/';
Object.values(RESULT_TYPES).forEach(type => {
  if (type.key === 'default') {
    type.image = 'img/raw.webp';
    return;
  }
  type.image = `${RESULT_IMAGE_BASE}${type.key}.webp`;
});
